[project]
name = "pfacd"
version = "0.1.0"
description = "Add a short description here"
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
python = ">=3.12.1,<3.13"
jupyter = ">=1.0.0,<1.1"
pandas = ">=2.2.0,<2.3"
pyarrow = ">=15.0.0,<15.1"
pyprojroot = ">=0.3.0,<0.4"
openpyxl = ">=3.1.2,<3.2"
cartopy = ">=0.22.0,<0.23"
# fiona = ">=1.9.5,<1.10"
icecream = ">=2.1.3,<2.2"
geopandas = ">=0.14.3,<0.15"
# folium = ">=0.15.1,<0.16"

[pypi-dependencies]
datar = ">= 0.15.5,<0.16"
