[project]
name = "pfacd"
version = "0.1.0"
description = "Add a short description here"
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tasks]

[dependencies]
python = ">=3.12.1,<3.13"
jupyter = ">=1.0.0,<1.1"
pandas = ">=2.2.0,<2.3"
pyarrow = ">=15.0.0,<15.1"
pyprojroot = ">=0.3.0,<0.4"    # for here
openpyxl = ">=3.1.2,<3.2"      # for read_excel
cartopy = ">=0.22.0,<0.23"     # for maps
# fiona = ">=1.9.5,<1.10"      # to read shape metadata
icecream = ">=2.1.3,<2.2"      # for debug
geopandas = ">=0.14.3,<0.15"
folium = ">=0.15.1,<0.16"      # leaflet
Imageio = ">=2.34.0,<2.35"
python-duckdb = ">=0.10.1,<0.11"
python-dateutil = ">=2.9.0,<2.10"
thefuzz = ">=0.22.1,<0.23"
unidecode = ">=1.3.8,<1.4"
pixi-pycharm = ">=0.0.4,<0.1"
plotnine = ">=0.13.4,<0.14"
jsonpath-ng = ">=1.6.1,<1.7"
pyogrio = ">=0.8.0,<0.9"
orjson = ">=3.10.3,<3.11"
tqdm = ">=4.66.4,<4.67"
requests = ">=2.32.2,<2.33"
# prettymaps = ">=1.0.0,<1.1"
# klib = ">=0.2.0,<0.3"        # data exploration lib

[pypi-dependencies]
datar = { version = ">=0.15.5,<0.16", extras = ["numpy", "pandas"] } # dplyr
pyjanitor = ">=0.26.0, <0.27"
duckdb-kernel = "*" # idk acho q n e preciso
skimpy = "*"
