import networkx as nx
import matplotlib.pyplot as plt


G = nx.Graph()


concelhos = [
    "Abrantes", "Águeda", "Aguiar da Beira", "Alandroal", "Albergaria-a-Velha", "Albufeira", 
    "Alcácer do Sal", "Alcanena", "Alcobaça", "Alcochete", "Alcoutim", "Alenquer", 
    "Alfândega da Fé", "Alijó", "Aljezur", "Aljustrel", "Almada", "Almeida", 
    "Almeirim", "Almodôvar", "Alpiarça", "Alvaiázere", "Alvito", "Amadora", 
    "Amarante", "Amares", "Anadia", "Angra do Heroísmo", "Ansião", "Arcos de Valdevez", 
    "Arganil", "Armamar", "Arouca", "Arraiolos", "Arronches", "Arruda dos Vinhos", 
    "Aveiro", "Avis", "Azambuja", "Baião", "Barcelos", "Barreiro", 
    "Batalha", "Beja", "Belmonte", "Benavente", "Borba", "Boticas", 
    "Braga", "Bragança", "Cabeceiras de Basto", "Cadaval", "Caldas da Rainha", "Calheta (Açores)", 
    "Calheta (Madeira)", "Câmara de Lobos", "Caminha", "Campo Maior", "Cantanhede", "Carrazeda de Ansiães", 
    "Carregal do Sal", "Cartaxo", "Cascais", "Castanheira de Pera", "Castelo Branco", "Castelo de Paiva", 
    "Castro Daire", "Castro Marim", "Castro Verde", "Celorico da Beira", "Celorico da Beira", "Celorico de Basto", 
    "Celorico de Basto", "Cernache", "Chamusca", "Chaves", "Cinfães", "Coimbra", 
    "Condeixa-a-Nova", "Constância", "Coruche", "Corvo", "Covilhã", "Crato", 
    "Cuba", "Cubos", "Elvas", "Entroncamento", "Espinho", "Esposende", 
    "Estarreja", "Estremoz", "Évora", "Fafe", "Faro", "Felgueiras", 
    "Ferreira do Alentejo", "Ferreira do Zêzere", "Figueira da Foz", "Figueira de Castelo Rodrigo", "Figueiró dos Vinhos", "Fornos de Algodres", 
    "Funchal", "Fundão", "Gavião", "Góis", "Golegã", "Gondomar", 
    "Gouveia", "Grândola", "Guarda", "Guimarães", "Horta", "Idanha-a-Nova", 
    "Ílhavo", "Lagoa (Algarve)", "Lagoa (Azores)", "Lagos", "Lajes das Flores", "Lajes do Pico", 
    "Lamego", "Leiria", "Lisboa", "Loulé", "Loures", "Lourinhã", 
    "Lousã", "Lousada", "Macedo de Cavaleiros", "Machico", "Madalena", "Mafra", 
    "Maia", "Mangualde", "Manteigas", "Marco de Canaveses", "Marinha Grande", "Marvão", 
    "Matosinhos", "Mealhada", "Mêda", "Melgaço", "Mértola", "Mesão Frio", 
    "Mira", "Miranda do Corvo", "Miranda do Douro", "Mirandela", "Mogadouro", "Moimenta da Beira", 
    "Moita", "Monção", "Monchique", "Mondim de Basto", "Monforte", "Montalegre", 
    "Montemor-o-Novo", "Montemor-o-Velho", "Montijo", "Mora", "Mortágua", "Moura", 
    "Mourão", "Murça", "Murtosa", "Nazaré", "Nelas", "Nisa", 
    "Nordeste", "Óbidos", "Odemira", "Odivelas", "Oeiras", "Oleiros", 
    "Olhão", "Oliveira de Azeméis", "Oliveira de Frades", "Oliveira do Bairro", "Oliveira do Hospital", "Ourém", 
    "Ourique", "Ovar", "Paços de Ferreira", "Palmela", "Pampilhosa da Serra", "Paredes", 
    "Paredes de Coura", "Pedrógão Grande", "Penacova", "Penafiel", "Penalva do Castelo", "Penamacor", 
    "Penedono", "Penela", "Peniche", "Peso da Régua", "Pinhel", "Pombal", 
    "Ponta Delgada", "Ponta do Sol", "Ponte da Barca", "Ponte de Lima", "Ponte de Sor", "Portalegre", 
    "Portel", "Portimão", "Porto", "Porto de Mós", "Porto Moniz", "Porto Santo", 
    "Póvoa de Lanhoso", "Póvoa de Varzim", "Povoação", "Praia da Vitória", "Proença-a-Nova", "Redondo", 
    "Reguengos de Monsaraz", "Resende", "Ribeira Brava", "Ribeira de Pena", "Ribeira Grande", "Rio Maior", 
    "Sabrosa", "Sabugal", "Salvaterra de Magos", "Santa Comba Dão", "Santa Cruz", "Santa Cruz da Graciosa", 
    "Santa Cruz das Flores", "Santa Maria da Feira", "Santa Marta de Penaguião", "Santana", "Santarém", "Santiago do Cacém", 
    "Santo Tirso", "São Brás de Alportel", "São João da Madeira", "São João da Pesqueira", "São Pedro do Sul", "São Roque do Pico", 
    "São Vicente", "Sardoal", "Sátão", "Seia", "Seixal", "Sernancelhe", 
    "Serpa", "Sertã", "Sesimbra", "Setúbal", "Sever do Vouga", "Silves", 
    "Sines", "Sintra", "Sobral de Monte Agraço", "Soure", "Sousel", "Tábua", 
    "Tabuaço", "Tarouca", "Tavira", "Terras de Bouro", "Tomar", "Tondela", 
    "Torre de Moncorvo", "Torres Novas", "Torres Vedras", "Trancoso", "Trofa", "Vagos", 
    "Vale de Cambra", "Valença", "Valongo", "Valpaços", "Velas", "Vendas Novas", 
    "Viana do Alentejo", "Viana do Castelo", "Vidigueira", "Vieira do Minho", "Vila de Rei", "Vila do Bispo", 
    "Vila do Conde", "Vila do Porto", "Vila Flor", "Vila Franca de Xira", "Vila Franca do Campo", "Vila Nova da Barquinha", 
    "Vila Nova de Cerveira", "Vila Nova de Famalicão", "Vila Nova de Foz Côa", "Vila Nova de Gaia", "Vila Nova de Paiva", "Vila Nova de Poiares", 
    "Vila Pouca de Aguiar", "Vila Real", "Vila Real de Santo António", "Vila Velha de Ródão", "Vila Verde", "Vila Viçosa", "Vimioso", 
    "Vinhais", "Viseu", "Vizela"]


G.add_nodes_from(concelhos)


# vizinhanca = [
#     ("Abrantes", "Constância"), ("Abrantes", "Mação"),
#     ("Águeda", "Albergaria-a-Velha"), ("Águeda", "Anadia"),
#     ("Aguiar da Beira", "Fornos de Algodres"), ("Aguiar da Beira", "Trancoso"),
#     ("Alandroal", "Borba"), ("Alandroal", "Vila Viçosa"),
#     ("Albergaria-a-Velha", "Águeda"), ("Albergaria-a-Velha", "Aveiro"),
#     ("Albufeira", "Lagoa"), ("Albufeira", "Silves"),
#     ("Alcácer do Sal", "Grândola"), ("Alcácer do Sal", "Montemor-o-Novo"),
#     ("Alcanena", "Entroncamento"), ("Alcanena", "Torres Novas"),
#     ("Alcobaça", "Caldas da Rainha"), ("Alcobaça", "Nazaré"),
#     ("Alcochete", "Moita"), ("Alcochete", "Montijo"),
#     ("Alcoutim", "Castro Marim"), ("Alcoutim", "Tavira"),
#     ("Alenquer", "Arruda dos Vinhos"), ("Alenquer", "Cadaval"),
#     ("Alfândega da Fé", "Macedo de Cavaleiros"), ("Alfândega da Fé", "Miranda do Douro"),
#     ("Alijó", "Carrazeda de Ansiães"), ("Alijó", "Sabrosa"),
#     ("Aljezur", "Lagos"), ("Aljezur", "Vila do Bispo"),
#     ("Aljustrel", "Ourique"), ("Aljustrel", "Odemira"),
#     ("Almada", "Seixal"), ("Almada", "Sesimbra"),
#     ("Almeida", "Figueira de Castelo Rodrigo"), ("Almeida", "Pinhel"),
#     ("Almeirim", "Cartaxo"), ("Almeirim", "Santarém"),
#     ("Almodôvar", "Odemira"), ("Almodôvar", "Ourique"),
#     ("Alpiarça", "Santarém"), ("Alpiarça", "Torres Novas"),
#     ("Alvaiázere", "Ansião"), ("Alvaiázere", "Figueiró dos Vinhos"),
#     ("Alvito", "Cuba"), ("Alvito", "Vidigueira"),
#     ("Amadora", "Lisboa"), ("Amadora", "Odivelas"),
#     ("Amarante", "Baião"), ("Amarante", "Marco de Canaveses"),
#     ("Amares", "Braga"), ("Amares", "Terras de Bouro"),
#     ("Anadia", "Aveiro"), ("Anadia", "Mealhada"),
#     ("Angra do Heroísmo", "Praia da Vitória"), ("Angra do Heroísmo", "Vila da Praia da Vitória"),
#     ("Ansião", "Figueiró dos Vinhos"), ("Ansião", "Pombal"),
#     ("Arcos de Valdevez", "Ponte da Barca"), ("Arcos de Valdevez", "Ponte de Lima"),
#     ("Arganil", "Góis"), ("Arganil", "Lousã"),
#     ("Armamar", "Lamego"), ("Armamar", "Peso da Régua"),
#     ("Arouca", "Oliveira de Azeméis"), ("Arouca", "Vale de Cambra"),
#     ("Arraiolos", "Montemor-o-Novo"), ("Arraiolos", "Mora"),
#     ("Arronches", "Campo Maior"), ("Arronches", "Elvas"),
#     ("Arruda dos Vinhos", "Loures"), ("Arruda dos Vinhos", "Sobral de Monte Agraço"),
#     ("Aveiro", "Ílhavo"), ("Aveiro", "Vagos"),
#     ("Avis", "Gavião"), ("Avis", "Ponte de Sor"),
#     ("Azambuja", "Cartaxo"), ("Azambuja", "Rio Maior"),
#     ("Baião", "Cinfães"), ("Baião", "Marco de Canaveses"),
#     ("Barcelos", "Esposende"), ("Barcelos", "Vila Verde"),
#     ("Barrancos", "Moura"), ("Barrancos", "Serpa"),
#     ("Barreiro", "Moita"), ("Barreiro", "Palmela"),
#     ("Batalha", "Leiria"), ("Batalha", "Marinha Grande"),
#     ("Beja", "Cuba"), ("Beja", "Moura"),
#     ("Belmonte", "Covilhã"), ("Belmonte", "Fundão"),
#     ("Benavente", "Coruche"), ("Benavente", "Salvaterra de Magos"),
#     ("Boticas", "Chaves"), ("Boticas", "Montalegre"),
#     ("Braga", "Guimarães"), ("Braga", "Vila Nova de Famalicão"),
#     ("Bragança", "Miranda do Douro"), ("Bragança", "Vinhais"),
#     ("Cabeceiras de Basto", "Fafe"), ("Cabeceiras de Basto", "Mondim de Basto"),
#     ("Cadaval", "Lourinhã"), ("Cadaval", "Sobral de Monte Agraço"),
#     ("Caldas da Rainha", "Óbidos"), ("Caldas da Rainha", "Peniche"),
#     ("Calheta", "Ponta do Sol"), ("Calheta", "Ribeira Brava"),
#     ("Calheta", "Santa Cruz"), ("Calheta", "São Vicente"),
#     ("Câmara de Lobos", "Funchal"), ("Câmara de Lobos", "Ribeira Brava"),
#     ("Caminha", "Paredes de Coura"), ("Caminha", "Vila Nova de Cerveira"),
#     ("Campo Maior", "Elvas"), ("Campo Maior", "Ouguela"),
#     ("Cantanhede", "Figueira da Foz"), ("Cantanhede", "Montemor-o-Velho"),
#     ("Carrazeda de Ansiães", "Macedo de Cavaleiros"), ("Carrazeda de Ansiães", "Vila Flor"),
#     ("Carregal do Sal", "Mangualde"), ("Carregal do Sal", "Nelas"),
#     ("Cartaxo", "Rio Maior"), ("Cartaxo", "Santarém"),
#     ("Cascais", "Oeiras"), ("Cascais", "Sintra"),
#     ("Castanheira de Pera", "Figueiró dos Vinhos"), ("Castanheira de Pera", "Pedrógão Grande"),
#     ("Castelo Branco", "Fundão"), ("Castelo Branco", "Idanha-a-Nova"),
#     ("Castelo de Paiva", "Arouca"), ("Castelo de Paiva", "Penafiel"),
#     ("Castelo de Vide", "Marvão"), ("Castelo de Vide", "Nisa"),
#     ("Castro Daire", "Cinfães"), ("Castro Daire", "Resende"),
#     ("Castro Marim", "Tavira"), ("Castro Marim", "Vila Real de Santo António"),
#     ("Castro Verde", "Mértola"), ("Castro Verde", "Ourique"),
#     ("Celorico da Beira", "Fornos de Algodres"), ("Celorico da Beira", "Guarda"),
#     ("Celorico de Basto", "Cabeceiras de Basto"), ("Celorico de Basto", "Fafe"),
#     ("Chamusca", "Coruche"), ("Chamusca", "Golegã"),
#     ("Chaves", "Montalegre"), ("Chaves", "Valpaços"),
#     ("Cinfães", "Resende"), ("Cinfães", "Vila Nova de Paiva"),
#     ("Coimbra", "Condeixa-a-Nova"), ("Coimbra", "Montemor-o-Velho"),
#     ("Condeixa-a-Nova", "Mealhada"), ("Condeixa-a-Nova", "Soure"),
#     ("Constância", "Sardoal"), ("Constância", "Tomar"),
#     ("Coruche", "Salvaterra de Magos"), ("Coruche", "Santarém"),
#     ("Corvo", "Flores"), ("Corvo", "Santa Cruz das Flores"),
#     ("Covilhã", "Fundão"), ("Covilhã", "Pampilhosa da Serra"),
#     ("Crato", "Alter do Chão"), ("Crato", "Portalegre"),
#     ("Cuba", "Ferreira do Alentejo"), ("Cuba", "Vidigueira"),
#     ("Elvas", "Campo Maior"), ("Elvas", "Monforte"),
#     ("Entroncamento", "Ourém"), ("Entroncamento", "Torres Novas"),
#     ("Espinho", "Santa Maria da Feira"), ("Espinho", "Vila Nova de Gaia"),
#     ("Esposende", "Barcelos"), ("Esposende", "Viana do Castelo"),
#     ("Estarreja", "Oliveira de Azeméis"), ("Estarreja", "Ovar"),
#     ("Estrondo", "Macedo de Cavaleiros"), ("Estrondo", "Mirandela"),
#     ("Évora", "Arraiolos"), ("Évora", "Montemor-o-Novo"),
#     ("Fafe", "Guimarães"), ("Fafe", "Mondim de Basto"),
#     ("Faro", "Loulé"), ("Faro", "Olhão"),
#     ("Felgueiras", "Amarante"), ("Felgueiras", "Lousada"),
#     ("Ferreira do Alentejo", "Beja"), ("Ferreira do Alentejo", "Serpa"),
#     ("Ferreira do Zêzere", "Sertã"), ("Ferreira do Zêzere", "Tomar"),
#     ("Figueira da Foz", "Leiria"), ("Figueira da Foz", "Montemor-o-Velho"),
#     ("Figueira de Castelo Rodrigo", "Pinhel"), ("Figueira de Castelo Rodrigo", "Trancoso"),
#     ("Figueiró dos Vinhos", "Leiria"), ("Figueiró dos Vinhos", "Pedrógão Grande"),
#     ("Fornos de Algodres", "Guarda"), ("Fornos de Algodres", "Mangualde"),
#     ("Funchal", "Câmara de Lobos"), ("Funchal", "Santa Cruz"),
#     ("Fundão", "Belmonte"), ("Fundão", "Covilhã"),
#     ("Gavião", "Abrantes"), ("Gavião", "Mação"),
#     ("Góis", "Arganil"), ("Góis", "Lousã"),
#     ("Golegã", "Santarém"), ("Golegã", "Tomar"),
#     ("Gondomar", "Maia"), ("Gondomar", "Valongo"),
#     ("Gouveia", "Manteigas"), ("Gouveia", "Seia"),
#     ("Grândola", "Alcácer do Sal"), ("Grândola", "Santiago do Cacém"),
#     ("Guarda", "Aguiar da Beira"), ("Guarda", "Manteigas"),
#     ("Guimarães", "Fafe"), ("Guimarães", "Vizela"),
#     ("Horta", "Lajes das Flores"), ("Horta", "Madalena"),
#     ("Ílhavo", "Aveiro"), ("Ílhavo", "Vagos"),
#     ("Lagoa", "Lagos"), ("Lagoa", "Portimão"),
#     ("Lagos", "Aljezur"), ("Lagos", "Vila do Bispo"),
#     ("Lajes das Flores", "Lajes do Pico"), ("Lajes das Flores", "Santa Cruz das Flores"),
#     ("Lajes do Pico", "Madalena"), ("Lajes do Pico", "São Roque do Pico"),
#     ("Lamego", "Armamar"), ("Lamego", "Peso da Régua"),
#     ("Leiria", "Marinha Grande"), ("Leiria", "Óbidos"),
#     ("Lisboa", "Amadora"), ("Lisboa", "Oeiras"),
#     ("Loulé", "Albufeira"), ("Loulé", "Silves"),
#     ("Loures", "Lisboa"), ("Loures", "Odivelas"),
#     ("Lourinhã", "Cadaval"), ("Lourinhã", "Torres Vedras"),
#     ("Lousã", "Arganil"), ("Lousã", "Miranda do Corvo"),
#     ("Lousada", "Amarante"), ("Lousada", "Paços de Ferreira"),
#     ("Mação", "Abrantes"), ("Mação", "Vila de Rei"),
#     ("Macedo de Cavaleiros", "Bragança"), ("Macedo de Cavaleiros", "Mirandela"),
#     ("Machico", "Santa Cruz"), ("Machico", "Santana"),
#     ("Madalena", "Lajes do Pico"), ("Madalena", "São Roque do Pico"),
#     ("Mafra", "Sintra"), ("Mafra", "Torres Vedras"),
#     ("Maia", "Matosinhos"), ("Maia", "Trofa"),
#     ("Mangualde", "Aguiar da Beira"), ("Mangualde", "Nelas"),
#     ("Manteigas", "Gouveia"), ("Manteigas", "Seia"),
#     ("Marco de Canaveses", "Amarante"), ("Marco de Canaveses", "Cinfães"),
#     ("Marinha Grande", "Batalha"), ("Marinha Grande", "Leiria"),
#     ("Marvão", "Castelo de Vide"), ("Marvão", "Portalegre"),
#     ("Matosinhos", "Leça da Palmeira"), ("Matosinhos", "Maia"),
#     ("Mealhada", "Anadia"), ("Mealhada", "Coimbra"),
#     ("Melgaço", "Arcos de Valdevez"), ("Melgaço", "Monção"),
#     ("Mértola", "Alcoutim"), ("Mértola", "Serpa"),
#     ("Mesão Frio", "Peso da Régua"), ("Mesão Frio", "Santa Marta de Penaguião"),
#     ("Mira", "Cantanhede"), ("Mira", "Vagos"),
#     ("Miranda do Corvo", "Lousã"), ("Miranda do Corvo", "Penela"),
#     ("Miranda do Douro", "Mogadouro"), ("Miranda do Douro", "Vimioso"),
#     ("Mirandela", "Bragança"), ("Mirandela", "Macedo de Cavaleiros"),
#     ("Mogadouro", "Freixo de Espada à Cinta"), ("Mogadouro", "Vimioso"),
#     ("Moimenta da Beira", "Armamar"), ("Moimenta da Beira", "São João da Pesqueira"),
#     ("Moita", "Alcochete"), ("Moita", "Barreiro"),
#     ("Monção", "Paredes de Coura"), ("Monção", "Valença"),
#     ("Monchique", "Loulé"), ("Monchique", "Portimão"),
#     ("Mondim de Basto", "Cabeceiras de Basto"), ("Mondim de Basto", "Ribeira de Pena"),
#     ("Monforte", "Avis"), ("Monforte", "Campo Maior"),
#     ("Montalegre", "Boticas"), ("Montalegre", "Chaves"),
#     ("Montemor-o-Novo", "Arraiolos"), ("Montemor-o-Novo", "Évora"),
#     ("Montemor-o-Velho", "Cantanhede"), ("Montemor-o-Velho", "Soure"),
#     ("Montijo", "Alcochete"), ("Montijo", "Palmela"),
#     ("Mora", "Coruche"), ("Mora", "Santarém"),
#     ("Mortágua", "Carregal do Sal"), ("Mortágua", "Santa Comba Dão"),
#     ("Moura", "Barrancos"), ("Moura", "Serpa"),
#     ("Mourão", "Reguengos de Monsaraz"), ("Mourão", "Viana do Alentejo"),
#     ("Murça", "Alijó"), ("Murça", "Vila Real"),
#     ("Murtosa", "Ovar"), ("Murtosa", "Vagos"),
#     ("Nazare", "Alcobaça"), ("Nazare", "Caldas da Rainha"),
#     ("Nelas", "Carregal do Sal"), ("Nelas", "Mangualde"),
#     ("Nisa", "Castelo de Vide"), ("Nisa", "Crato"),
#     ("Nordeste", "Povoação"), ("Nordeste", "Ribeira Grande"),
#     ("Óbidos", "Caldas da Rainha"), ("Óbidos", "Peniche"),
#     ("Odemira", "Aljustrel"), ("Odemira", "Ourique"),
#     ("Odivelas", "Amadora"), ("Odivelas", "Loures"),
#     ("Oeiras", "Amadora"), ("Oeiras", "Cascais"),
#     ("Oleiros", "Castanheira de Pera"), ("Oleiros", "Sertã"),
#     ("Olhão", "Faro"), ("Olhão", "Tavira"),
#     ("Oliveira de Azeméis", "Arouca"), ("Oliveira de Azeméis", "Vale de Cambra"),
#     ("Oliveira de Frades", "Carregal do Sal"), ("Oliveira de Frades", "Vouzela"),
#     ("Oliveira do Bairro", "Anadia"), ("Oliveira do Bairro", "Águeda"),
#     ("Oliveira do Hospital", "Arganil"), ("Oliveira do Hospital", "Tábua"),
#     ("Ourém", "Alcanena"), ("Ourém", "Tomar"),
#     ("Ourique", "Aljustrel"), ("Ourique", "Castro Verde"),
#     ("Ovar", "Estarreja"), ("Ovar", "Santa Maria da Feira"),
#     ("Palmela", "Alcochete"), ("Palmela", "Setúbal"),
#     ("Pampilhosa da Serra", "Arganil"), ("Pampilhosa da Serra", "Oleiros"),
#     ("Paredes", "Amarante"), ("Paredes", "Valongo"),
#     ("Paredes de Coura", "Caminha"), ("Paredes de Coura", "Valença"),
#     ("Paredes de Escud", "Valongo"), ("Paredes de Escud", "Vila Nova de Gaia"),
#     ("Ponte da Barca", "Arcos de Valdevez"), ("Ponte da Barca", "Ponte de Lima"),
#     ("Ponte de Lima", "Arcos de Valdevez"), ("Ponte de Lima", "Ponte da Barca"),
#     ("Ponte de Sor", "Avis"), ("Ponte de Sor", "Gavião"),
#     ("Portalegre", "Castelo de Vide"), ("Portalegre", "Marvão"),
#     ("Portel", "Viana do Alentejo"), ("Portel", "Vila Viçosa"),
#     ("Portimão", "Lagoa"), ("Portimão", "Monchique"),
#     ("Porto", "Gondomar"), ("Porto", "Matosinhos"),
#     ("Porto de Mós", "Alcobaça"), ("Porto de Mós", "Leiria"),
#     ("Póvoa de Lanhoso", "Braga"), ("Póvoa de Lanhoso", "Fafe"),
#     ("Póvoa de Varzim", "Esposende"), ("Póvoa de Varzim", "Vila do Conde"),
#     ("Povoação", "Nordeste"), ("Povoação", "Ribeira Grande"),
#     ("Praia da Vitória", "Angra do Heroísmo"), ("Praia da Vitória", "Vila da Praia da Vitória"),
#     ("Proença-a-Nova", "Oleiros"), ("Proença-a-Nova", "Vila de Rei"),
#     ("Redondo", "Évora"), ("Redondo", "Vila Viçosa"),
#     ("Reguengos de Monsaraz", "Mourão"), ("Reguengos de Monsaraz", "Viana do Alentejo"),
#     ("Resende", "Cinfães"), ("Resende", "Lamego"),
#     ("Ribeira Brava", "Calheta"), ("Ribeira Brava", "Ponta do Sol"),
#     ("Ribeira de Pena", "Mondim de Basto"), ("Ribeira de Pena", "Vila Real"),
#     ("Ribeira Grande", "Nordeste"), ("Ribeira Grande", "Povoação"),
#     ("Rio Maior", "Alenquer"), ("Rio Maior", "Azambuja"),
#     ("Sabrosa", "Alijó"), ("Sabrosa", "Vila Real"),
#     ("Sabugal", "Almeida"), ("Sabugal", "Celorico da Beira"),
#     ("Salvaterra de Magos", "Benavente"), ("Salvaterra de Magos", "Coruche"),
#     ("Santa Comba Dão", "Mortágua"), ("Santa Comba Dão", "Tondela"),
#     ("Santa Cruz", "Machico"), ("Santa Cruz", "Santa Cruz"),
#     ("Santa Cruz da Graciosa", "Santa Cruz das Flores"), ("Santa Cruz da Graciosa", "Velas"),
#     ("Santa Cruz das Flores", "Lajes das Flores"), ("Santa Cruz das Flores", "Santa Cruz da Graciosa"),
#     ("Santa Maria da Feira", "Espinho"), ("Santa Maria da Feira", "Oliveira de Azeméis"),
#     ("Santa Marta de Penaguião", "Mesão Frio"), ("Santa Marta de Penaguião", "Peso da Régua"),
#     ("Santana", "Machico"), ("Santana", "São Vicente"),
#     ("Santarém", "Almeirim"), ("Santarém", "Alpiarça"),
#     ("Santiago do Cacém", "Alcácer do Sal"), ("Santiago do Cacém", "Sines"),
#     ("Santo Tirso", "Maia"), ("Santo Tirso", "Trofa"),
#     ("São Brás de Alportel", "Loulé"), ("São Brás de Alportel", "Tavira"),
#     ("São João da Madeira", "Oliveira de Azeméis"), ("São João da Madeira", "Santa Maria da Feira"),
#     ("São João da Pesqueira", "Moimenta da Beira"), ("São João da Pesqueira", "Tabuaço"),
#     ("São Pedro do Sul", "Castro Daire"), ("São Pedro do Sul", "Vouzela"),
#     ("São Roque do Pico", "Madalena"), ("São Roque do Pico", "Lajes do Pico"),
#     ("São Vicente", "Porto Moniz"), ("São Vicente", "Santana"),
#     ("Sardoal", "Abrantes"), ("Sardoal", "Constância"),
#     ("Sátão", "Aguiar da Beira"), ("Sátão", "Viseu"),
#     ("Seia", "Gouveia"), ("Seia", "Oliveira do Hospital"),
#     ("Seixal", "Almada"), ("Seixal", "Setúbal"),
#     ("Sernancelhe", "Aguiar da Beira"), ("Sernancelhe", "Tabuaço"),
#     ("Serpa", "Mértola"), ("Serpa", "Moura"),
#     ("Sertã", "Oleiros"), ("Sertã", "Proença-a-Nova"),
#     ("Sesimbra", "Almada"), ("Sesimbra", "Setúbal"),
#     ("Setúbal", "Palmela"), ("Setúbal", "Sesimbra"),
#     ("Sever do Vouga", "Águeda"), ("Sever do Vouga", "Oliveira de Frades"),
#     ("Silves", "Albufeira"), ("Silves", "Lagoa"),
#     ("Sines", "Grândola"), ("Sines", "Santiago do Cacém"),
#     ("Sintra", "Cascais"), ("Sintra", "Mafra"),
#     ("Sobral de Monte Agraço", "Arruda dos Vinhos"), ("Sobral de Monte Agraço", "Torres Vedras"),
#     ("Soure", "Condeixa-a-Nova"), ("Soure", "Montemor-o-Velho"),
#     ("Sousel", "Avis"), ("Sousel", "Fronteira"),
#     ("Tábua", "Arganil"), ("Tábua", "Oliveira do Hospital"),
#     ("Tabuaço", "Penedono"), ("Tabuaço", "São João da Pesqueira"),
#     ("Tarouca", "Armamar"), ("Tarouca", "Lamego"),
#     ("Tavira", "Faro"), ("Tavira", "São Brás de Alportel"),
#     ("Terras de Bouro", "Amares"), ("Terras de Bouro", "Póvoa de Lanhoso"),
#     ("Tomar", "Constância"), ("Tomar", "Ourém"),
#     ("Tondela", "Carregal do Sal"), ("Tondela", "Santa Comba Dão"),
#     ("Torre de Moncorvo", "Carrazeda de Ansiães"), ("Torre de Moncorvo", "Vila Flor"),
#     ("Torres Novas", "Alcanena"), ("Torres Novas", "Entroncamento"),
#     ("Torres Vedras", "Lourinhã"), ("Torres Vedras", "Sobral de Monte Agraço"),
#     ("Trancoso", "Aguiar da Beira"), ("Trancoso", "Figueira de Castelo Rodrigo"),
#     ("Trofa", "Maia"), ("Trofa", "Valongo"),
#     ("Vagos", "Aveiro"), ("Vagos", "Ílhavo"),
#     ("Vale de Cambra", "Arouca"), ("Vale de Cambra", "Sever do Vouga"),
#     ("Valença", "Monção"), ("Valença", "Paredes de Coura"),
#     ("Valongo", "Gondomar"), ("Valongo", "Paredes"),
#     ("Valpaços", "Chaves"), ("Valpaços", "Vila Pouca de Aguiar"),
#     ("Velas", "Lajes das Flores"), ("Velas", "Santa Cruz da Graciosa"),
#     ("Vendas Novas", "Montemor-o-Novo"), ("Vendas Novas", "Vila Viçosa"),
#     ("Viana do Alentejo", "Alcácer do Sal"), ("Viana do Alentejo", "Montemor-o-Novo"),
#     ("Viana do Castelo", "Caminha"), ("Viana do Castelo", "Ponte de Lima"),
#     ("Vidigueira", "Beja"), ("Vidigueira", "Cuba"),
#     ("Vieira do Minho", "Cabeceiras de Basto"), ("Vieira do Minho", "Póvoa de Lanhoso"),
#     ("Vila de Rei", "Mação"), ("Vila de Rei", "Proença-a-Nova"),
#     ("Vila do Bispo", "Lagos"), ("Vila do Bispo", "Vila do Bispo"),
#     ("Vila do Conde", "Esposende"), ("Vila do Conde", "Póvoa de Varzim"),
#     ("Vila do Porto", "Santa Cruz da Graciosa"), ("Vila do Porto", "Vila do Porto"),
#     ("Vila Flor", "Carrazeda de Ansiães"), ("Vila Flor", "Torre de Moncorvo"),
#     ("Vila Franca de Xira", "Azambuja"), ("Vila Franca de Xira", "Loures"),
#     ("Vila Franca do Campo", "Lagoa"), ("Vila Franca do Campo", "Ponta Delgada"),
#     ("Vila Nova da Barquinha", "Abrantes"), ("Vila Nova da Barquinha", "Constância"),
#     ("Vila Nova de Cerveira", "Caminha"), ("Vila Nova de Cerveira", "Valença"),
#     ("Vila Nova de Famalicão", "Braga"), ("Vila Nova de Famalicão", "Guimarães"),
#     ("Vila Nova de Foz Côa", "Alijó"), ("Vila Nova de Foz Côa", "Mêda"),
#     ("Vila Nova de Gaia", "Espinho"), ("Vila Nova de Gaia", "Vila do Conde"),
#     ("Vila Nova de Paiva", "Castro Daire"), ("Vila Nova de Paiva", "Viseu"),
#     ("Vila Nova de Poiares", "Arganil"), ("Vila Nova de Poiares", "Lousã"),
#     ("Vila Pouca de Aguiar", "Chaves"), ("Vila Pouca de Aguiar", "Ribeira de Pena"),
#     ("Vila Real", "Mondim de Basto"), ("Vila Real", "Sabrosa"),
#     ("Vila Real de Santo António", "Castro Marim"), ("Vila Real de Santo António", "Tavira"),
#     ("Vila Velha de Ródão", "Castelo Branco"), ("Vila Velha de Ródão", "Proença-a-Nova"),
#     ("Vila Verde", "Amares"), ("Vila Verde", "Braga"),
#     ("Vila Viçosa", "Borba"), ("Vila Viçosa", "Redondo"),
#     ("Vimioso", "Bragança"), ("Vimioso", "Mogadouro"),
#     ("Vinhas", "Penedono"), ("Vinhas", "Tabuaço"),
#     ("Viseu", "Mangualde"), ("Viseu", "Nelas"),
#     ("Vizela", "Felgueiras"), ("Vizela", "Guimarães"),
#     ("Vouzela", "Oliveira de Frades"), ("Vouzela", "São Pedro do Sul"),
   
# ]

concelhos_vizinhos = {
    "Abrantes": ["Constância", "Sardoal", "Tomar", "Vila Nova da Barquinha"],
    "Águeda": ["Albergaria-a-Velha", "Anadia", "Aveiro", "Oliveira do Bairro"],
    "Aguiar da Beira": ["Fornos de Algodres", "Gouveia", "Mangualde", "Trancoso"],
    "Alandroal": ["Arraiolos", "Borba", "Évora", "Vila Viçosa"],
    "Albergaria-a-Velha": ["Águeda", "Anadia", "Oliveira do Bairro", "Sever do Vouga"],
    "Albufeira": ["Loulé", "Silves"],
    "Alcácer do Sal": ["Grândola", "Palmela", "Santiago do Cacém"],
    "Alcanena": ["Entroncamento", "Ourém", "Santarém", "Tomar"],
    "Alcobaça": ["Caldas da Rainha", "Leiria", "Marinha Grande", "Nazaré", "Óbidos"],
    "Alcochete": ["Barreiro", "Moita", "Palmela", "Santarém"],
    "Alcoutim": ["Castro Marim", "Tavira"],
    "Alenquer": ["Azambuja", "Cadaval", "Sobral de Monte Agraço", "Torres Vedras"],
    "Alfândega da Fé": ["Carrazeda de Ansiães", "Macedo de Cavaleiros", "Mirandela", "Vimioso"],
    "Alijó": ["Carrazeda de Ansiães", "Murça", "Peso da Régua", "Sabrosa"],
    "Aljezur": ["Lagos", "Vila do Bispo"],
    "Aljustrel": ["Ferreira do Alentejo", "Ourique", "Serpa"],
    "Almada": ["Lisboa", "Seixal", "Sesimbra"],
    "Almeida": ["Figueira de Castelo Rodrigo", "Guarda", "Pinhel", "Sabugal", "Vila Nova de Foz Côa"],
    "Almeirim": ["Cartaxo", "Coruche", "Rio Maior", "Santarém"],
    "Almodôvar": ["Ourique", "Silves"],
    "Alpiarça": ["Benavente", "Cartaxo", "Santarém", "Tomar"],
    "Alvaiázere": ["Ansião", "Figueiró dos Vinhos", "Leiria", "Pombal"],
    "Alvito": ["Beja", "Cuba", "Ferreira do Alentejo"],
    "Amadora": ["Lisboa", "Odivelas", "Sintra"],
    "Amarante": ["Baião", "Felgueiras", "Freamunde", "Lousada", "Marco de Canaveses", "Mondim de Basto", "Paredes", "Vila Real"],
    "Amares": ["Braga", "Póvoa de Lanhoso", "Terras de Bouro", "Vieira do Minho"],
    "Anadia": ["Águeda", "Albergaria-a-Velha", "Aveiro", "Cantanhede"],
    "Angra do Heroísmo": ["Praia da Vitória"],
    "Ansião": ["Alvaiázere", "Castanheira de Pera", "Figueiró dos Vinhos", "Leiria", "Pombal"],
    "Arcos de Valdevez": ["Melgaço", "Paredes de Coura", "Ponte da Barca", "Ponte de Lima", "Terras de Bouro", "Viana do Castelo"],
    "Arganil": ["Góis", "Lousã", "Oliveira do Hospital", "Pampilhosa da Serra", "Tábua"],
    "Armamar": ["Lamego", "Lamego", "Penedono", "Resende"],
    "Arouca": ["Castelo de Paiva", "Espinho", "Oliveira de Azeméis", "São João da Madeira", "Santa Maria da Feira", "Sever do Vouga", "Vale de Cambra"],
    "Arraiolos": ["Alandroal", "Estremoz", "Évora", "Montemor-o-Novo", "Mora", "Sousel", "Vendas Novas"],
    "Arronches": ["Campo Maior", "Castelo de Vide", "Marvão"],
    "Arruda dos Vinhos": ["Loures", "Sobral de Monte Agraço", "Torres Vedras"],
    "Aveiro": ["Águeda", "Anadia", "Espinho", "Ílhavo", "Oliveira de Azeméis", "Ovar", "Santa Maria da Feira", "Vagos"],
    "Avis": ["Alter do Chão", "Arraiolos", "Crato", "Fronteira", "Ponte de Sor"],
    "Azambuja": ["Alenquer", "Arruda dos Vinhos", "Cartaxo", "Santarém", "Sobral de Monte Agraço", "Torres Novas", "Vila Franca de Xira"],
    "Baião": ["Amarante", "Cinfães", "Marco de Canaveses", "Resende"],
    "Barcelos": ["Esposende", "Ponte de Lima", "Viana do Castelo", "Vila Verde"],
    "Barreiro": ["Alcochete", "Moita", "Palmela", "Seixal"],
    "Batalha": ["Leiria", "Marinha Grande", "Ourém", "Pombal"],
    "Beja": ["Aljustrel", "Almodôvar", "Ferreira do Alentejo", "Mértola", "Serpa", "Vidigueira"],
    "Belmonte": ["Covilhã", "Fundão", "Guarda", "Manteigas", "Sabugal"],
    "Benavente": ["Almeirim", "Cartaxo", "Coruche", "Salvaterra de Magos", "Santarém", "Vila Franca de Xira"],
    "Borba": ["Alandroal", "Estremoz", "Évora", "Vila Viçosa"],
    "Boticas": ["Chaves", "Montalegre", "Ribeira de Pena", "Valpaços"],
    "Braga": ["Amares", "Barcelos", "Cabeceiras de Basto", "Fafe", "Guimarães", "Póvoa de Lanhoso", "Terras de Bouro", "Vieira do Minho", "Vila Nova de Famalicão"],
    "Bragança": ["Alfândega da Fé", "Carrazeda de Ansiães", "Freixo de Espada à Cinta", "Mirandela", "Miranda do Douro", "Mogadouro", "Torre de Moncorvo", "Vila Flor", "Vimioso"],
    "Cabeceiras de Basto": ["Celorico de Basto", "Fafe", "Mondim de Basto", "Ribeira de Pena"],
    "Cadaval": ["Alenquer", "Bombarral", "Lourinhã", "Óbidos", "Peniche", "Sobral de Monte Agraço", "Torres Vedras"],
    "Caldas da Rainha": ["Alcobaça", "Bombarral", "Nazaré", "Óbidos", "Peniche"],
    "Calheta (Açores)": ["Ponta do Sol (Madeira)", "Praia da Vitória"],
    "Calheta (Madeira)": ["Ponta do Sol (Madeira)", "Ribeira Brava (Madeira)"],
    "Câmara de Lobos": ["Funchal (Madeira)", "Ribeira Brava (Madeira)", "Santa Cruz (Madeira)"],
    "Caminha": ["Paredes de Coura", "Valença", "Viana do Castelo"],
    "Campo Maior": ["Arronches", "Elvas", "Fronteira", "Monforte"],
    "Cantanhede": ["Águeda", "Anadia", "Coimbra", "Figueira da Foz", "Mealhada", "Mira", "Montemor-o-Velho", "Soure"],
    "Carrazeda de Ansiães": ["Alijó", "Freixo de Espada à Cinta", "Mogadouro", "Torre de Moncorvo", "Vila Flor"],
    "Carregal do Sal": ["Mangualde", "Nelas", "Oliveira do Hospital", "Tábua"],
    "Cartaxo": ["Almeirim", "Azambuja", "Benavente", "Entroncamento", "Santarém", "Tomar", "Vila Franca de Xira"],
    "Cascais": ["Lisboa", "Oeiras", "Sintra"],
    "Castanheira de Pera": ["Figueiró dos Vinhos", "Leiria", "Pedrógão Grande"],
    "Castelo Branco": ["Belmonte", "Fundão", "Idanha-a-Nova", "Oleiros", "Penamacor", "Proença-a-Nova", "Vila de Rei"],
    "Castelo de Paiva": ["Arouca", "Cinfães", "Marco de Canaveses", "Penafiel", "Resende"],
    "Castro Daire": ["Cinfães", "Lamego", "Mangualde", "Moimenta da Beira", "Nelas", "Santa Comba Dão", "São Pedro do Sul", "Tarouca", "Viseu"],
    "Castro Marim": ["Alcoutim", "Tavira", "Vila Real de Santo António"],
    "Castro Verde": ["Almodôvar", "Aljustrel", "Beja", "Mértola", "Ourique"],
    "Celorico da Beira": ["Fornos de Algodres", "Gouveia", "Guarda", "Mangualde", "Manteigas", "Nelas", "Oliveira do Hospital", "Seia"],
    "Celorico de Basto": ["Cabeceiras de Basto", "Fafe", "Mondim de Basto", "Ribeira de Pena"],
    "Cernache": ["Coimbra", "Miranda do Corvo", "Penela"],
    "Chamusca": ["Abrantes", "Almeirim", "Coruche", "Golegã", "Salvaterra de Magos", "Santarém"],
    "Chaves": ["Boticas", "Mondim de Basto", "Montalegre", "Ribeira de Pena", "Valpaços", "Verín (Espanha)", "Vila Pouca de Aguiar"],
    "Cinfães": ["Amarante", "Castro Daire", "Castro Daire", "Castro Daire", "Lamego", "Resende", "São João da Pesqueira", "Sernancelhe", "Tarouca"],
    "Coimbra": ["Cantanhede", "Condeixa-a-Nova", "Figueira da Foz", "Lousã", "Mira", "Montemor-o-Velho", "Oliveira do Hospital", "Pampilhosa da Serra", "Penacova", "Penela", "Soure"],
    "Condeixa-a-Nova": ["Coimbra", "Montemor-o-Velho", "Penela"],
    "Constância": ["Abrantes", "Entroncamento", "Sardoal", "Tomar", "Vila Nova da Barquinha"],
    "Coruche": ["Almeirim", "Benavente", "Chamusca", "Mora", "Santarém"],
    "Corvo": ["Flores", "Santa Cruz das Flores"],
    "Covilhã": ["Belmonte", "Fundão", "Gouveia", "Manteigas", "Oleiros", "Penamacor", "Seia", "Vila de Rei"],
    "Crato": ["Alter do Chão", "Avis", "Castelo de Vide", "Fronteira", "Nisa", "Ponte de Sor"],
    "Cuba": ["Alvito", "Beja", "Vidigueira"],
    "Cubos": ["Mogadouro", "Vimioso"],
    "Elvas": ["Campo Maior", "Monforte"],
    "Entroncamento": ["Alcanena", "Constância", "Golegã", "Santarém", "Tomar", "Torres Novas", "Vila Nova da Barquinha"],
    "Espinho": ["Arouca", "Oliveira de Azeméis", "Santa Maria da Feira"],
    "Esposende": ["Barcelos", "Viana do Castelo"],
    "Estarreja": ["Aveiro", "Murtosa", "Oliveira de Azeméis", "Ovar", "Santa Maria da Feira"],
    "Estremoz": ["Arraiolos", "Borba", "Évora", "Sousel", "Vila Viçosa"],
    "Évora": ["Alandroal", "Arraiolos", "Borba", "Estremoz", "Montemor-o-Novo", "Mora", "Redondo", "Reguengos de Monsaraz", "Vendas Novas", "Viana do Alentejo", "Vila Viçosa"],
    "Fafe": ["Amarante", "Cabeceiras de Basto", "Celorico de Basto", "Guimarães", "Mondim de Basto", "Póvoa de Lanhoso", "Vieira do Minho"],
    "Faro": ["Loulé", "Olhão", "São Brás de Alportel", "Tavira", "Vila Real de Santo António"],
    "Felgueiras": ["Amarante", "Lousada", "Paços de Ferreira", "Paredes", "Penafiel"],
    "Ferreira do Alentejo": ["Aljustrel", "Beja", "Mértola", "Ourique"],
    "Ferreira do Zêzere": ["Ourém", "Sertã", "Tomar"],
    "Figueira da Foz": ["Cantanhede", "Coimbra", "Leiria", "Montemor-o-Velho", "Pombal", "Soure"],
    "Figueira de Castelo Rodrigo": ["Almeida", "Mêda", "Pinhel", "Sabugal"],
    "Figueiró dos Vinhos": ["Alvaiázere", "Ansiao", "Castanheira de Pera", "Leiria", "Pedrógão Grande"],
    "Fornos de Algodres": ["Aguiar da Beira", "Celorico da Beira", "Gouveia", "Guarda", "Mangualde", "Nelas"],
    "Funchal": ["Câmara de Lobos", "Machico", "Ponta do Sol", "Porto Moniz", "Ribeira Brava", "Santa Cruz", "Santana"],
    "Fundão": ["Belmonte", "Castelo Branco", "Covilhã", "Idanha-a-Nova", "Penamacor", "Proença-a-Nova", "Vila de Rei"],
    "Gavião": ["Abrantes", "Alter do Chão", "Crato", "Nisa"],
    "Góis": ["Arganil", "Lousã", "Miranda do Corvo", "Pampilhosa da Serra"],
    "Golegã": ["Chamusca", "Entroncamento", "Santarém", "Tomar", "Torres Novas", "Vila Nova da Barquinha"],
    "Gondomar": ["Maia", "Paredes", "Porto", "Valongo"],
    "Gouveia": ["Aguiar da Beira", "Celorico da Beira", "Fornos de Algodres", "Guarda", "Mangualde", "Manteigas", "Nelas", "Seia", "Trancoso"],
    "Grândola": ["Alcácer do Sal", "Alcácer do Sal", "Melides", "Santiago do Cacém"],
    "Guarda": ["Aguiar da Beira", "Almeida", "Celorico da Beira", "Figueira de Castelo Rodrigo", "Fornos de Algodres", "Gouveia", "Pinhel", "Sabugal", "Seia", "Trancoso", "Vila Nova de Foz Côa"],
    "Guimarães": ["Amares", "Fafe", "Felgueiras", "Póvoa de Lanhoso", "Vieira do Minho", "Vizela"],
    "Horta": ["Lajes das Flores", "Lajes do Pico"],
    "Idanha-a-Nova": ["Castelo Branco", "Fundão", "Oleiros", "Penamacor", "Proença-a-Nova", "Vila de Rei"],
    "Ílhavo": ["Aveiro", "Vagos"],
    "Lagoa (Algarve)": ["Lagoa (Azores)", "Portimão", "Silves"],
    "Lagoa (Azores)": ["Lagoa (Madeira)", "Ponta Delgada", "Ribeira Grande", "Vila Franca do Campo"],
    "Lagos": ["Aljezur", "Vila do Bispo"],
    "Lajes das Flores": ["Horta", "Santa Cruz das Flores"],
    "Lajes do Pico": ["Horta", "São Roque do Pico"],
    "Lamego": ["Armamar", "Celorico da Beira", "Cinfães", "Penedono", "Resende", "São João da Pesqueira", "Tabuaço", "Tarouca"],
    "Leiria": ["Alcobaça", "Alvaiázere", "Ansião", "Batalha", "Bombarral", "Castanheira de Pera", "Figueiró dos Vinhos", "Marinha Grande", "Nazaré", "Óbidos", "Pedrógão Grande", "Pombal", "Porto de Mós"],
    "Lisboa": ["Almada", "Amadora", "Cascais", "Loures", "Mafra", "Odivelas", "Oeiras", "Sintra", "Vila Franca de Xira"],
    "Loulé": ["Albufeira", "Faro", "Silves"],
    "Lourinhã": ["Bombarral", "Cadaval", "Peniche", "Torres Vedras"],
    "Lousã": ["Arganil", "Castanheira de Pera", "Góis", "Miranda do Corvo", "Penela"],
    "Lousada": ["Amarante", "Felgueiras", "Paços de Ferreira", "Penafiel"],
    "Macedo de Cavaleiros": ["Alfândega da Fé", "Bragança", "Mirandela", "Miranda do Douro", "Vila Flor"],
    "Machico": ["Funchal", "Santa Cruz"],
    "Madalena": ["Lajes do Pico", "São Roque do Pico"],
    "Mafra": ["Lisboa", "Sintra", "Torres Vedras"],
    "Maia": ["Gondomar", "Matosinhos", "Porto", "Santo Tirso", "Trofa", "Valongo", "Vila do Conde"],
    "Mangualde": ["Aguiar da Beira", "Celorico da Beira", "Fornos de Algodres", "Gouveia", "Nelas", "Penalva do Castelo", "Sátão", "Tondela", "Viseu"],
    "Manteigas": ["Belmonte", "Covilhã", "Fornos de Algodres", "Gouveia", "Guarda", "Seia"],
    "Marco de Canaveses": ["Amarante", "Baião", "Castelo de Paiva", "Cinfães", "Paredes", "Penafiel"],
    "Marinha Grande": ["Alcobaça", "Leiria", "Óbidos", "Pombal"],
    "Marvão": ["Arronches", "Castelo de Vide", "Nisa", "Portalegre"],
    "Matosinhos": ["Maia", "Porto", "Póvoa de Varzim", "Santo Tirso", "Trofa", "Vila do Conde"],
    "Mealhada": ["Águeda", "Anadia", "Cantanhede", "Coimbra"],
    "Melgaço": ["Arcos de Valdevez", "Monção", "Paredes de Coura", "Valença"],
    "Mértola": ["Alcoutim", "Almodôvar", "Aljustrel", "Beja", "Castro Verde"],
    "Mesão Frio": ["Amarante", "Peso da Régua", "Santa Marta de Penaguião"],
    "Mira": ["Cantanhede", "Coimbra", "Montemor-o-Velho", "Vagos"],
    "Miranda do Corvo": ["Arganil", "Góis", "Lousã", "Penela"],
    "Miranda do Douro": ["Bragança", "Macedo de Cavaleiros", "Mogadouro", "Vinhais"],
    "Mirandela": ["Alfândega da Fé", "Bragança", "Macedo de Cavaleiros", "Mogadouro", "Vila Flor"],
    "Mirandela": ["Alfândega da Fé", "Bragança", "Macedo de Cavaleiros", "Mogadouro", "Vila Flor"],
    "Mirandela": ["Alfândega da Fé", "Bragança", "Macedo de Cavaleiros", "Mogadouro", "Vila Flor"],
    "Mogadouro": ["Alfândega da Fé", "Carrazeda de Ansiães", "Castro Daire", "Freixo de Espada à Cinta", "Macedo de Cavaleiros", "Miranda do Douro", "Vila Flor"],
    "Moimenta da Beira": ["Armamar", "Castro Daire", "São João da Pesqueira", "Tarouca", "Vila Nova de Paiva"],
    "Moita": ["Alcochete", "Barreiro", "Montijo", "Palmela", "Seixal", "Sesimbra"],
    "Monção": ["Melgaço", "Paredes de Coura", "Valença"],
    "Monforte": ["Campo Maior", "Elvas", "Fronteira"],
    "Montalegre": ["Boticas", "Chaves", "Terras de Bouro", "Valpaços", "Vinhais"],
    "Montemor-o-Novo": ["Arraiolos", "Évora", "Mora", "Redondo", "Vendas Novas", "Viana do Alentejo"],
    "Montemor-o-Velho": ["Cantanhede", "Condeixa-a-Nova", "Coimbra", "Figueira da Foz", "Soure"],
    "Montijo": ["Alcochete", "Moita", "Palmela", "Sesimbra"],
    "Morão": ["Castelo de Vide", "Nisa"],
    "Mortágua": ["Anadia", "Santa Comba Dão", "Tondela", "Vouzela"],
    "Moura": ["Barrancos", "Beja", "Serpa"],
    "Mourão": ["Alandroal", "Arraiolos", "Évora", "Reguengos de Monsaraz"],
    "Murça": ["Alijó", "Carrazeda de Ansiães", "Peso da Régua", "Sabrosa", "Vila Real"],
    "Murtosa": ["Arouca", "Estarreja", "Ovar", "Santa Maria da Feira"],
    "Nelas": ["Aguiar da Beira", "Celorico da Beira", "Fornos de Algodres", "Mangualde", "Mortágua", "Penalva do Castelo", "Sátão", "Tondela", "Viseu"],
    "Nisa": ["Castelo Branco", "Crato", "Gavião", "Marvão", "Morão"],
    "Nordeste": ["Povoação", "Ribeira Grande", "Vila Franca do Campo"],
    "Óbidos": ["Alcobaça", "Alvaiázere", "Bombarral", "Caldas da Rainha", "Lourinhã", "Peniche"],
    "Odemira": ["Aljezur", "Almodôvar", "Ourique", "Santiago do Cacém", "São Teotónio", "Sines"],
    "Odivelas": ["Amadora", "Lisboa", "Loures", "Sintra", "Vila Franca de Xira"],
    "Oeiras": ["Amadora", "Cascais", "Lisboa", "Sintra"],
    "Oleiros": ["Castelo Branco", "Covilhã", "Fundão", "Idanha-a-Nova", "Penamacor", "Proença-a-Nova", "Vila de Rei"],
    "Olhão": ["Faro", "Tavira"],
    "Oliveira de Azeméis": ["Águeda", "Espinho", "Estarreja", "Ovar", "Santa Maria da Feira", "São João da Madeira"],
    "Oliveira de Frades": ["Águeda", "Carregal do Sal", "Santa Comba Dão", "Tondela", "Viseu"],
    "Oliveira do Bairro": ["Águeda", "Anadia", "Aveiro", "Vagos"],
    "Oliveira do Hospital": ["Arganil", "Carregal do Sal", "Covilhã", "Góis", "Seia", "Tábua"],
    "Ourém": ["Alcanena", "Alvaiázere", "Batalha", "Fátima", "Ferreira do Zêzere", "Leiria", "Tomar"],
    "Ourique": ["Aljustrel", "Almodôvar", "Castro Verde", "Odemira"],
    "Ovar": ["Aveiro", "Estarreja", "Murtosa", "Santa Maria da Feira"],
    "Palmela": ["Alcácer do Sal", "Alcochete", "Moita", "Montijo", "Palmela", "Santiago do Cacém", "Sesimbra", "Setúbal", "Sines"],
    "Pampilhosa da Serra": ["Arganil", "Figueira da Foz", "Góis", "Oliveira do Hospital", "Penela"],
    "Paredes": ["Amarante", "Felgueiras", "Lousada", "Paços de Ferreira", "Penafiel"],
    "Paredes de Coura": ["Arcos de Valdevez", "Melgaço", "Monção", "Ponte da Barca", "Valença", "Vila Nova de Cerveira"],
    "Pedrógão Grande": ["Castanheira de Pera", "Figueiró dos Vinhos", "Leiria"],
    "Penacova": ["Arganil", "Coimbra", "Miranda do Corvo", "Montemor-o-Velho", "Penela", "Tábua"],
    "Penafiel": ["Castelo de Paiva", "Felgueiras", "Lousada", "Paredes"],
    "Penalva do Castelo": ["Aguiar da Beira", "Fornos de Algodres", "Mangualde", "Nelas", "Sátão", "Tondela", "Viseu"],
    "Penamacor": ["Belmonte", "Castelo Branco", "Idanha-a-Nova", "Oleiros", "Proença-a-Nova"],
    "Penedono": ["Armamar", "Lamego", "Sernancelhe", "Tabuaço", "Tarouca"],
    "Penela": ["Coimbra", "Figueiró dos Vinhos", "Lousã", "Miranda do Corvo", "Penacova"],
    "Peniche": ["Caldas da Rainha", "Lourinhã", "Óbidos"],
    "Peso da Régua": ["Alijó", "Celorico da Beira", "Mesão Frio", "Murça", "Santa Marta de Penaguião"],
    "Pinhel": ["Almeida", "Celorico da Beira", "Figueira de Castelo Rodrigo", "Guarda", "Mêda", "Sabugal"],
    "Pombal": ["Alvaiázere", "Ansião", "Cantanhede", "Castanheira de Pera", "Figueira da Foz", "Leiria", "Soure"],
    "Ponta Delgada": ["Lagoa (Azores)", "Nordeste", "Ribeira Grande"],
    "Ponta do Sol (Madeira)": ["Calheta (Madeira)", "Ribeira Brava (Madeira)", "Santa Cruz (Madeira)", "São Vicente (Madeira)"],
    "Ponta do Sol (Madeira)": ["Calheta (Madeira)", "Ribeira Brava (Madeira)", "Santa Cruz (Madeira)", "São Vicente (Madeira)"],
    "Ponte da Barca": ["Arcos de Valdevez", "Paredes de Coura", "Pontede Lima"],
    "Ponte de Lima": ["Arcos de Valdevez", "Barcelos", "Ponte da Barca"],
    "Ponte de Sor": ["Avis", "Crato", "Gavião", "Mora"],
    "Portalegre": ["Arronches", "Avis", "Campo Maior", "Castelo de Vide", "Crato", "Fronteira", "Marvão", "Monforte", "Nisa"],
    "Portel": ["Évora", "Montemor-o-Novo", "Viana do Alentejo", "Vila Viçosa"],
    "Portimão": ["Lagoa (Algarve)", "Lagos", "Silves"],
    "Porto": ["Gondomar", "Maia", "Matosinhos", "Póvoa de Varzim", "Santo Tirso", "Trofa", "Valongo", "Vila do Conde", "Vila Nova de Gaia"],
    "Porto Moniz": ["Funchal", "Santana"],
    "Porto Santo": ["Funchal"],
    "Póvoa de Lanhoso": ["Amares", "Fafe", "Guimarães", "Vieira do Minho"],
    "Póvoa de Varzim": ["Matosinhos", "Porto", "Vila do Conde"],
    "Povoação": ["Nordeste", "Ribeira Grande", "Vila Franca do Campo"],
    "Praia da Vitória": ["Angra do Heroísmo", "Calheta (Açores)"],
    "Proença-a-Nova": ["Belmonte", "Castelo Branco", "Covilhã", "Idanha-a-Nova", "Oleiros", "Penamacor", "Vila de Rei"],
    "Redondo": ["Évora", "Montemor-o-Novo", "Vendas Novas", "Vila Viçosa"],
    "Reguengos de Monsaraz": ["Évora", "Mourão", "Portel"],
    "Resende": ["Armamar", "Cinfães", "Lamego", "Paredes de Coura"],
    "Ribeira Brava (Madeira)": ["Calheta (Madeira)", "Câmara de Lobos", "Ponta do Sol (Madeira)", "Santa Cruz (Madeira)", "Santana (Madeira)"],
    "Ribeira Brava": ["Funchal", "Machico", "Porto Moniz", "Santana", "Santa Cruz"],
    "Ribeira Grande": ["Lagoa (Azores)", "Nordeste", "Ponta Delgada"],
    "Rio Maior": ["Almeirim", "Cartaxo", "Santarém", "Torres Novas"],
    "Sabrosa": ["Alijó", "Murça", "Peso da Régua", "Vila Real"],
    "Sabugal": ["Almeida", "Figueira de Castelo Rodrigo", "Mêda", "Pinhel"],
    "Salvaterra de Magos": ["Benavente", "Chamusca", "Coruche", "Santarém"],
    "Santa Comba Dão": ["Castro Daire", "Mortágua", "Nelas", "Oliveira de Frades", "Tondela"],
    "Santa Cruz (Madeira)": ["Calheta (Madeira)", "Câmara de Lobos", "Ponta do Sol (Madeira)", "Ribeira Brava (Madeira)", "Santana (Madeira)"],
    "Santa Cruz": ["Funchal", "Machico", "Porto Moniz", "Ribeira Brava", "Santana"],
    "Santa Maria da Feira": ["Arouca", "Espinho", "Oliveira de Azeméis", "Ovar", "São João da Madeira", "Vagos", "Vale de Cambra"],
    "Santa Marta de Penaguião": ["Mesão Frio", "Peso da Régua", "Vila Real"],
    "Santana": ["Funchal", "Porto Moniz", "Ribeira Brava", "Santa Cruz"],
    "Santana (Madeira)": ["Funchal", "Ribeira Brava (Madeira)", "Santa Cruz (Madeira)", "São Vicente (Madeira)"],
    "Santiago do Cacém": ["Alcácer do Sal", "Grândola", "Melides", "Odemira", "Sines"],
    "Santo Tirso": ["Gondomar", "Maia", "Matosinhos", "Porto", "Póvoa de Varzim", "Trofa", "Valongo", "Vila do Conde"],
    "São Brás de Alportel": ["Faro", "Loulé", "São Brás de Alportel"],
    "São João da Madeira": ["Oliveira de Azeméis", "Santa Maria da Feira"],
    "São João da Pesqueira": ["Armamar", "Carregal do Sal", "Lamego", "Moimenta da Beira", "Penedono", "Sernancelhe", "Tabuaço"],
    "São Pedro do Sul": ["Castro Daire", "Viseu"],
    "São Roque do Pico": ["Lajes do Pico", "Madalena"],
    "São Teotónio": ["Almodôvar", "Odemira", "Odemira"],
    "São Vicente (Madeira)": ["Calheta (Madeira)", "Ponta do Sol (Madeira)", "Ribeira Brava (Madeira)", "Santana (Madeira)"],
    "Sardoal": ["Abrantes", "Constância", "Tomar", "Vila Nova da Barquinha"],
    "Sátão": ["Aguiar da Beira", "Mangualde", "Nelas", "Oliveira de Frades", "Penalva do Castelo", "Viseu"],
    "Seia": ["Celorico da Beira", "Covilhã", "Gouveia", "Mangualde", "Nelas", "Oliveira do Hospital"],
    "Seixal": ["Almada", "Barreiro", "Moita", "Sesimbra"],
    "Sernancelhe": ["Aguiar da Beira", "Cinfães", "Lamego", "Moimenta da Beira", "Penedono", "São João da Pesqueira", "Tabuaço", "Vila Nova de Paiva"],
    "Serpa": ["Aljustrel", "Beja", "Mértola", "Moura"],
    "Sertã": ["Abrantes", "Ferreira do Zêzere", "Oleiros", "Proença-a-Nova", "Tomar"],
    "Sesimbra": ["Almada", "Barreiro", "Moita", "Palmela", "Seixal"],
    "Setúbal": ["Alcácer do Sal", "Alcochete", "Barreiro", "Moita", "Palmela", "Santiago do Cacém", "Sesimbra", "Sines"],
    "Sever do Vouga": ["Águeda", "Albergaria-a-Velha", "Oliveira de Azeméis", "Vagos"],
    "Silves": ["Lagoa (Algarve)", "Lagoa (Algarve)", "Loulé", "Portimão"],
    "Sines": ["Alcácer do Sal", "Grândola", "Odemira", "Santiago do Cacém"],
}
for concelho, vizinhos in concelhos_vizinhos.items():
    for vizinho in vizinhos:
        G.add_edge(concelho, vizinho)


# Visualizar o grafo
nx.draw(G, with_labels=True, font_weight='bold')
plt.show()